### PR TITLE
Fix out of bounds panic

### PR DESCRIPTION
**Pull request by timtadh**
See #18 

This is not yet finished.

### CODE REVIEW

**Comment by timtadh** [comment]
@xaionaro let me know if this solves the problem for you. Additionally, the issue was caused by your ID tokens which match the empty string. You may not want to do that (change the `*` into a `+`).

**Comment by xaionaro** [comment]
Yep, it helped, indeed. Thank you!

> You may not want to do that (change the * into a +).

Ok, my bad. Thanks :)

**Comment by xaionaro** [comment]
BTW, seems, you added extra `fmt.Println` to the code.

**Comment by timtadh** [comment]
kk merging

**Pull request merged**
